name: ci

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node env 📦
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          registry-url: https://registry.npmjs.org
          scope: '@geoql'

      - name: Upgrade npm 🎉
        run: npm install -g npm@latest

      - name: Get npm cache directory 🏗
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Restore cached node_modules 🤷‍♂️
        uses: actions/cache@v2.1.6
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 🚀
        run: npm ci --prefer-offline --no-audit --no-optional

      - name: Run linter(s) 👀
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          continue_on_error: false
          git_name: github-actions[bot]
          git_email: github-actions[bot]@users.noreply.github.com
          auto_fix: false
          stylelint: true
          stylelint_extensions: css,scss,vue
          eslint: true
          eslint_extensions: js,ts,vue
          prettier: true
          prettier_extensions: js,ts,vue
          neutral_check_on_warning: true

      - name: Build the package 🎉
        run: npm run build
